services:
  db:
    image: ####### 
    container_name: #######
    restart: #######
    environment:
      POSTGRES_DB: #######
      POSTGRES_USER: #######
      POSTGRES_PASSWORD: #######
    ports:
      - #######
    volumes:
      - #######

volumes:
  #######:
